FROM node:14 as builder

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json if available
COPY package.json package-lock.json* ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Command to run the application
RUN npm run build

FROM nginx:alpine

# Copy the build output to the nginx html directory
COPY --from=builder /app/build /usr/share/nginx/html
